cmake_minimum_required(VERSION 3.8)
project(kinect2_calibration)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(OpenCV REQUIRED)
find_package(cv_bridge REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(message_filters REQUIRED)
find_package(image_transport REQUIRED)
find_package(kinect2_bridge REQUIRED)
find_package(kinect2_registration REQUIRED)
find_package(OpenMP QUIET)
add_executable(kinect2_calibration_node src/kinect2_calibration.cpp)
target_include_directories(kinect2_calibration_node PRIVATE include)
ament_target_dependencies(kinect2_calibration_node rclcpp OpenCV cv_bridge
  sensor_msgs message_filters image_transport kinect2_bridge kinect2_registration)
if(OpenMP_CXX_FOUND)
  target_link_libraries(kinect2_calibration_node OpenMP::OpenMP_CXX)
endif()
install(TARGETS kinect2_calibration_node DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY patterns DESTINATION share/${PROJECT_NAME})
install(FILES LICENSE DESTINATION share/${PROJECT_NAME})
install(PROGRAMS scripts/convert_calib_pose_to_urdf_format.py DESTINATION lib/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(calibration_offline test/test_calibration.py TIMEOUT 120)
endif()
ament_package()
